<a href="https://colab.research.google.com/github/Ziannnniiii/2025_AI_TI1B/blob/main/job2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Jobsheet 2 perasi matematika, matriks, vektor, dan tipe data

# Latihan 2

In [8]:
import math

# a. Mendapatkan nilai minimum dan maksimum
x_min = min(5, 10, 25)
y_max = max(6, 12, 18)

# b. Mendapatkan nilai absolut
x_abs = abs(-7.25)

# c. Mendapatkan nilai pangkat
x_pow = math.pow(4, 3)  # 4^3 = 64

# d. Mendapatkan nilai akar
x_sqrt = math.sqrt(64)  # √64 = 8

# e. Mendapatkan nilai pembulatan
x_ceil = math.ceil(1.4)  # Dibulatkan ke atas -> 2
y_floor = math.floor(1.4)  # Dibulatkan ke bawah -> 1

# Menampilkan hasil
print(f"Nilai minimum: {x_min}")
print(f"Nilai maksimum: {y_max}")
print(f"Nilai absolut: {x_abs}")
print(f"Nilai pangkat (4^3): {x_pow}")
print(f"Nilai akar (√64): {x_sqrt}")
print(f"Pembulatan ke atas (ceil 1.4): {x_ceil}")
print(f"Pembulatan ke bawah (floor 1.4): {y_floor}")

Nilai minimum: 5
Nilai maksimum: 18
Nilai absolut: 7.25
Nilai pangkat (4^3): 64.0
Nilai akar (√64): 8.0
Pembulatan ke atas (ceil 1.4): 2
Pembulatan ke bawah (floor 1.4): 1


# Latihan 3

In [9]:
import math

def main():
    x = math.radians(45)  # Konversi derajat ke radian
    y = 5
    z = 2

    print(f"sin(45°): {math.sin(x)}")
    print(f"cos(45°): {math.cos(x)}")
    print(f"tan(45°): {math.tan(x)}")
    print(f"log({y}): {math.log(y)}")
    print(f"log10({y}): {math.log10(y)}")
    print(f"90 derajat dalam radian: {math.degrees(math.pi / 2)}")
    print(f"Jarak Euclidean antara (0,0) dan (3,4): {math.dist([0, 0], [3, 4])}")
    print(f"Faktorial dari {z}: {math.factorial(z)}")
    print(f"Modulus floating point dari 5.3 % 2.1: {math.fmod(5.3, 2.1)}")
    print(f"Apakah NaN (Not a Number)?: {math.isnan(float('nan'))}")
    print(f"Gamma dari 5: {math.gamma(5)}")
    print(f"Permutasi 5P2: {math.perm(5, 2)}")

if __name__ == "__main__":
    main()


sin(45°): 0.7071067811865475
cos(45°): 0.7071067811865476
tan(45°): 0.9999999999999999
log(5): 1.6094379124341003
log10(5): 0.6989700043360189
90 derajat dalam radian: 90.0
Jarak Euclidean antara (0,0) dan (3,4): 5.0
Faktorial dari 2: 2
Modulus floating point dari 5.3 % 2.1: 1.0999999999999996
Apakah NaN (Not a Number)?: True
Gamma dari 5: 24.0
Permutasi 5P2: 20


# Latihan 4

In [11]:
import numpy as np

# Membuat matriks di Python
A = np.array([[80, 30, 25],
              [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])
hasil_matriks = A + B

# Melakukan operasi dot product
A_dot = np.array([10, 20, 15])
B_dot = np.array([16, 67, 35])
hasil_dot = np.dot(A_dot, B_dot)

# Melakukan operasi cross product
A_cross = np.array([10, 20, 15])
B_cross = np.array([16, 67, 35])
hasil_cross = np.cross(A_cross, B_cross)

# Menampilkan hasil
print("Hasil Penjumlahan Matriks:")
print(hasil_matriks)
print("\nHasil Dot Product:", hasil_dot)
print("\nHasil Cross Product:", hasil_cross)

Hasil Penjumlahan Matriks:
[[110  90  40]
 [ 60  50  40]]

Hasil Dot Product: 2025

Hasil Cross Product: [-305 -110  350]


# Praktikum 1

In [12]:
import numpy as np

# Definisi matriks
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Perkalian A x B
AB = np.dot(A, B)
print("Hasil A x B:\n", AB)

# Perkalian B x C
BC = np.dot(B, C)
print("\nHasil B x C:\n", BC)

Hasil A x B:
 [[7 2]
 [4 2]]

Hasil B x C:
 [[ 0  2  3]
 [-3  1  3]]


# Praktikum 2

In [13]:
import math

# a. Menghitung 6!
faktorial_6 = math.factorial(6)
print("6! =", faktorial_6)

# b. Menghitung 8! / 5!
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)
hasil = faktorial_8 / faktorial_5
print("8! / 5! =", hasil)

6! = 720
8! / 5! = 336.0


## Praktikum 3

In [15]:
import numpy as np

# Vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Panjang vektor (norma)
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Perkalian titik (dot product)
dot_product = np.dot(A, B)

# Perkalian silang (cross product)
cross_product = np.cross(A, B)

# Menampilkan hasil
print(f"Panjang vektor A: {panjang_A:.2f}")
print(f"Panjang vektor B: {panjang_B:.2f}")
print(f"Perkalian titik (A . B): {dot_product}")
print(f"Perkalian silang (A x B): {cross_product}")


Panjang vektor A: 9.11
Panjang vektor B: 12.41
Perkalian titik (A . B): 58
Perkalian silang (A x B): [ 24  79 -51]
